"""Email drafting tool — generates professional supplier/internal communications."""


def draft_supplier_email(
    supplier_name: str,
    contact_name: str,
    contact_email: str,
    subject: str,
    context: str,
    urgency: str = "high",
) -> dict:
    """Draft a professional email to a supplier contact.

    Args:
        supplier_name: Name of the supplier company.
        contact_name: Name of the contact person.
        contact_email: Email address of the contact.
        subject: Email subject line.
        context: Context about the situation requiring communication.
        urgency: Urgency level — "low", "medium", "high", "critical".

    Returns:
        Complete email draft ready for review and sending.
    """
    urgency_prefix = {
        "critical": "[URGENT] ",
        "high": "[Priority] ",
        "medium": "",
        "low": "",
    }

    full_subject = f"{urgency_prefix.get(urgency, '')}{subject}"

    body = f"""Dear {contact_name},

I hope this message finds you well. I am writing on behalf of AutoParts GmbH regarding an urgent matter affecting our supply chain operations.

{context}

Given the criticality of this situation to our production schedules and downstream customer commitments, we would appreciate:

1. An updated delivery timeline for all affected shipments
2. Confirmation of any alternative fulfillment routes being explored
3. A call with your logistics team at the earliest convenience to discuss mitigation options

We value our partnership with {supplier_name} and want to work collaboratively to minimize impact on both our organizations.

Please respond at your earliest convenience. If this requires escalation on your end, we are happy to coordinate with your senior management team.

Best regards,
Procurement Team
AutoParts GmbH
Frankfurt, Germany
"""

    return {
        "type": "email",
        "to": contact_email,
        "to_name": contact_name,
        "supplier": supplier_name,
        "subject": full_subject,
        "body": body,
        "urgency": urgency,
        "status": "draft",
        "note": "Email drafted and ready for review. Will not be sent until approved.",
    }


def draft_internal_escalation(
    recipient_name: str,
    recipient_role: str,
    disruption_summary: str,
    financial_impact_eur: float,
    recommended_actions: str,
) -> dict:
    """Draft an internal escalation brief for executives.

    Args:
        recipient_name: Name of the internal recipient.
        recipient_role: Role/title of the recipient.
        disruption_summary: Brief summary of the disruption event.
        financial_impact_eur: Estimated financial impact in EUR.
        recommended_actions: Summary of recommended mitigation actions.

    Returns:
        Internal escalation brief document.
    """
    brief = f"""INTERNAL ESCALATION BRIEF — SUPPLY CHAIN DISRUPTION
{'='*60}
Classification: CONFIDENTIAL
Generated by: Warden Supply Chain Intelligence
Date: 2026-03-03

TO: {recipient_name}, {recipient_role}
FROM: Supply Chain Operations (Warden AI Co-Pilot)

EXECUTIVE SUMMARY
{'-'*40}
{disruption_summary}

FINANCIAL IMPACT
{'-'*40}
Estimated Revenue at Risk: €{financial_impact_eur:,.0f}
Impact Confidence: 73%

RECOMMENDED ACTIONS
{'-'*40}
{recommended_actions}

NEXT STEPS
{'-'*40}
1. Review and approve pending mitigation actions in Warden dashboard
2. Schedule emergency supply chain meeting (suggested: within 24 hours)
3. Authorize emergency procurement budget if Option A (air freight) is selected

This brief was auto-generated by Warden AI. All recommended actions require human approval before execution.
"""

    return {
        "type": "escalation",
        "recipient": recipient_name,
        "role": recipient_role,
        "content": brief,
        "financial_impact_eur": financial_impact_eur,
        "status": "draft",
    }


def draft_customer_communication(
    customer_name: str,
    contact_role: str,
    order_id: str,
    situation_summary: str,
    proposed_resolution: str,
) -> dict:
    """Draft a proactive customer communication about potential delivery impacts.

    Args:
        customer_name: Name of the customer company.
        contact_role: Role to address (e.g. "Account Manager").
        order_id: Affected order ID.
        situation_summary: Brief summary of the situation.
        proposed_resolution: What you're doing to resolve it.

    Returns:
        Customer communication draft.
    """
    body = f"""Dear {customer_name} {contact_role},

I am reaching out proactively regarding Order {order_id} to keep you informed of a developing situation in our supply chain.

SITUATION:
{situation_summary}

OUR RESPONSE:
{proposed_resolution}

We are committed to transparency and minimizing any impact on your operations. Our team is actively working on mitigation strategies and will provide a detailed update within 48 hours.

We value our partnership and want to ensure this is handled with the urgency it deserves. Please don't hesitate to reach out if you'd like to discuss this further.

Sincerely,
AutoParts GmbH
Supply Chain Operations
"""

    return {
        "type": "customer_email",
        "customer": customer_name,
        "order_id": order_id,
        "body": body,
        "status": "draft",
    }
